### ISSUE TITLE
Add instructions to clean up objects created during the lab (especially IAM roles that prevent CFN delete)

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/asynchronous-messaging-workshop#10]
Lab 1 cleanup fails due to the custom IAM role:
Cannot delete entity, must delete policies first. (Service: AmazonIdentityManagement; Status Code: 409; Error Code: DeleteConflict; ...
The following resource(s) failed to delete: [SubmitRideCompletionFunctionRole].
so I think this role needs to be deleted by hand.

Similarly, all manually created artifacts need delete instrucitons.
For example: the SNS topic created in lab 1 stays untouched, so following Lab 2 instructions brings me back to SNS with the topic and subscriptions I'm supposed to create already there...

**Comment by sliedig** [comment]
resolved in PR #19
