### ISSUE TITLE
3 small bugs in Lab2

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/asynchronous-messaging-workshop#26]
-	Bug with raw message format delivery:
When retesting please make sure both “SAM-way” and “Console-way” is tested. We have found a bug in the workshop last week preventing successful completion of “Console-way”. This was about “raw message delivery” for SNS subscriptions which was enabled in “SAM-way” but disabled in “Console-way”.
Also the way “Console-way” suggests creating the subscription does not allow for setting “raw message delivery” easily. More instruction is required.
On the other hand disabling “raw message delivery” breaks lambda functions processing messages.
I thought fixing the lambdas would be easier than adding more instructions so I patched lambdas in my fork in quick & dirty way.

-	Clean-up instruction for “Console-way” is incomplete and will result in CloudFormation stack deletion failure. I believe similar issues has been fixed in lab-1 – not sure why those changes are not applied consistently to all labs?

-	Minor documentation problems indicating IAM role should have 3 policies while it should actually be 2 policies. Not a biggie but does confuse the attendees.

**Comment by sliedig** [comment]
Partially resolved content issues. Clean up instructions moved to new issue. Thanks for raising this!

**Comment by winmaxim** [comment]
THANK YOU!!

Max

On Jun 25, 2021, at 6:25 AM, Stephen Liedig ***@***.***> wrote:

﻿

Partially resolved content issues. Clean up instructions moved to new issue. Thanks for raising this!
