### ISSUE TITLE
Cloud9 is missing Python 3.7 (and Linux2)

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/asynchronous-messaging-workshop#27]
sam build now throws this error for all labs:
Error: PythonPipBuilder:Validation - Binary validation failed for python, searched for python in following locations  : ['/usr/bin/python'] which did not satisfy constraints for runtime: python3.7. Do you have python for runtime: python3.7 on your PATH?

I think you need to specify Amazon Linux 2 per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html in the C9 template.

**Comment by sliedig** [comment]
Blueprint and modules in EE have been updated to include AL2.
