### ISSUE TITLE
Lab 2: Instruction issues

### ISSUE THREAD

**Issue by marcinbelczewski** [aws-samples/asynchronous-messaging-workshop#33]
Step 5 in https://async-messaging.workshop.aws/topic-queue-chaining-and-load-balancer/create-customer-accounting-service-subscription/create-customer-accounting-service-subscription.html contains 

Step 6 in https://async-messaging.workshop.aws/topic-queue-chaining-and-load-balancer/create-extraordinary-rides-service-subscription/create-extraordinary-rides-service-subscription.html have wrong titles referring to Notification Service while it should be Accounting Service and Extraordinary Rides Service respectively.

**Comment by sliedig** [comment]
Thanks for raising this. Issue has been resolved.
