### ISSUE TITLE
Adjust the "create SNS topic" step - Lab 1

### ISSUE THREAD

**Issue by lpiedade** [aws-samples/asynchronous-messaging-workshop#5]
After the release of the new feature "SNS FIFO Topics", the default topic type became FIFO when users are creating one by AWS Console. The problem occurs in Labs 1, when workshop attendees create a new topic using the default values, in the next step it is not possible to create the subscription using HTTP protocol.

The image should be updated as follows: 
![step-2-console](https://user-images.githubusercontent.com/510345/100492466-16b08300-310b-11eb-843b-cd757ea06bae.png)

**Comment by sliedig** [comment]
Thanks @lpiedade, this issue is now resolved!
