### ISSUE TITLE
Update needed to SNS creation step screenshot/instrucitons 

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/asynchronous-messaging-workshop#6]
It looks like the SNS creation step (https://async-messaging.workshop.aws/fan-out-and-message-filtering/create-sns-topic/create-sns-topic.html) has fallen out of sync with the AWS Console (which now looks like this and requires you to select FIFO or Standard).
Could you please update the workshop to reflect this (and add the extra step of switching to Standard or adding the .fifo suffix to the queue name?
![image](https://user-images.githubusercontent.com/68556857/108289330-3da3b180-715c-11eb-98f1-108acf6f48ed.png)

**Comment by sliedig** [comment]
Duplicate issue #5
