### ISSUE TITLE
Please simplify instructions for getting SNS topic ARN

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/asynchronous-messaging-workshop#7]
in https://async-messaging.workshop.aws/fan-out-and-message-filtering/update-unicorn-management-service/update-unicorn-management-service.html it would be clearer to simply ask the user to copy-paste the whole topic ARN from SNS.
The current instructions encourage the user to construct the ARN one piece at a time for no reason.

and similarly confusing is the lambda function code section, which tells the user to add code (and goes to immense trouble to hide that code in cheat sheets) when the code is already present in the lambda (just commented).

the instructions also neglect to tell the user to click Deploy after the function changes are made

![image](https://user-images.githubusercontent.com/68556857/108289538-94a98680-715c-11eb-9503-dbcc11f4fd09.png)

**Comment by sliedig** [comment]
Thanks for reporting this @winmaxim , I have updated the screenshots and instructions
