### ISSUE TITLE
re-sync SAM instructions to new CLI prompts 

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/asynchronous-messaging-workshop#9]
I've noticed the SAM default instructions were slightly wrong (and somewhat confusing).
The instructions say "Confirm the first 4 proposed arguments by hitting ENTER. When you get asked SubmitRideCompletionFunction may not have authorization defined, Is this okay? [y/N]:, enter y and hit ENTER again 2 times."
but there are now 3, not 2 prompts at the end.

**Comment by sliedig** [comment]
Updated SAM instruction to make it clearer (hopefully ;-))
